version: "3.4"

services:
  db:
    image: orientdb:2.2.30
    ports: 
      - "2424:2424"
      - "2480:2480"
    environment: 
      ORIENTDB_ROOT_PASSWORD: shitsuji
    volumes:
      - db_config:/orientdb/config
      - db_data:/orientdb/databases
      - db_backup:/orientdb/backup
  proxy:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - proxy_cert
      - proxy_dhparam
      - proxy_key
    environment:
      PROXY_HOST: "${HOST_IP}"
      PROXY_PORT: 5000
  # app:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/shitsuji

volumes:
  db_config:
  db_data:
  db_backup:

secrets:
  proxy_cert:
    file: ./nginx/secrets/cert.crt
  proxy_dhparam:
    file: ./nginx/secrets/dhparam.pem
  proxy_key:
    file: ./nginx/secrets/key.pem