version: "3.4"

services:
  db:
    image: orientdb:2.2.30
    ports: 
      - "2424:2424"
      - "2480:2480"
    environment: 
      ORIENTDB_ROOT_PASSWORD: shitsuji
    volumes:
      - db_config:/orientdb/config
      - db_data:/orientdb/databases
      - db_backup:/orientdb/backup
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/shitsuji
    environment:
      # SHITSUJI_CONFIG_FILE: # location of config file for the api itself
      # SHITSUJI_CONFIG_STORAGE_PATH: # path where the repositories are going to be saved
      # SHITSUJI_CONFIG_SECRET: # secret phrase used to 
      # SHITSUJI_REPOSITORY_CONFIG_FILE_PATH: # location of config file, together with name of the file in you projects
      # ORIENTDB_OPTS_FILE
      # ORIENTDB_HOST:
      # ORIENTDB_PORT:
      # ORIENTDB_USER:
      # ORIENTDB_PASSWORD:
      # ORIENTDB_DB_NAME:
      # ORIENTDB_DB_USER:
      # ORIENTDB_DB_PASSWORD:


volumes:
  db_config:
  db_data:
  db_backup: